##############################################################################
# For more information on parameters, refer to: 
# https://docs.gramaddict.org/#/configuration?id=configuration-file
#
# Note: be sure to comment out any parameters not used by adding a # in front
# AGAIN: YOU DON'T HAVE TO DELETE THE LINE, BUT ONLY COMMENT IT WITH A #!
##############################################################################
# General Configuration
##############################################################################

username:  # you have to put your IG name here!
device: e7ddc274 #R3CNC0EFCKV # e7ddc274 # put_your_device_id_there # 'adb devices' in the console to know it.  It's needed only if you have more than 1 device connected
app-id: com.instagram.android
use-cloned-app: false
screen-sleep: true
screen-record: false
speed-multiplier: 5
debug: false
close-apps: false
disable-block-detection: false
disable-filters: false
dont-type: false
# scrape-to-file: scraped.txt
total-crashes-limit: 5
count-app-crashes: false
shuffle-jobs: true
truncate-sources: 999

##############################################################################
# Actions
##############################################################################

## Interaction (active jobs)
blogger-followers: [tabuhenna,troll_canada_,canada_wale_yaar,surrey.waale,jashan.beauty,arjandhillonofficial,canadian_educator ,surrey.mehndi_art,thesurreymemes,bts.bighitofficial ,ajitroad_instant_confessions,red_leaf_ale ,pakke_canadawale,deep.dadzz_kaur,eyemakeup.videos,ishq_vichara,honiisandhuofficial,needlebox_by_pns,__madeforher__ ,__madeforher__,sangtarr,glam.fashionhub ,mamtadosanjh ,jattisquad,tera.fufad,ap.dhillxn, canadaian_student,immigrationnewscanada.ca ,canada_wale_yaar01,thisismastaani ,bramalea.rd,bhangraempire]
#
#blogger-followers: [ theweeknd]
#blogger-following: [ pakke_canadawale]
#blogger-post-likers: [thesurreymemes,troll_canada_,canada_wale_yaar01,canada_wale_yaar01canada_wale_yaar,honiisandhuofficial,jashan.beauty,needlebox_by_pns,canadaian_student,surrey.waale,jattisquad,tera.fufad,deep.dadzz_kaur,pakke_canadawale,red_leaf_ale,ajitroad_instant_confessions,bhangraempire,bramalea.rd,ap.dhillxn]
#blogger: [emmkay_23]
#hashtag-likers-top: [ niagrafalls, Whistler,Tofino,Churchill, CNTower]
#hashtag-likers-recent: [ niagrafalls, Whistler,Tofino,Churchill, CNTower]
#hashtag-posts-top: [ niagrafalls, Whistler,Tofino,Churchill, CNTower]
#hashtag-posts-recent: [ niagrafalls, Whistler,Tofino,Churchill, CNTower]
#place-posts-top: [ niagrafalls, Whistler,Tofino,Churchill, CNTower]
#place-posts-recent: [ niagra falls, Whistler,Tofino,Churchill, CNTower]
#place-likers-top: [ niagrafalls, Whistler,Tofino,Churchill, CNTower]
#place-likers-recent: [ niagrafalls, Whistler,Tofino,Churchill, CNTower]
#interact-from-file: [usernames1.txt 10-15, usernames2.txt 3]
#posts-from-file: posts.txt
#feed: 2-5 # is the number of likes you will give in feed

## Special modifier for jobs and sources
#watch-video-time: 15-35
#watch-photo-time: 3-4
# can-reinteract-after: 48 # the amount of hours that have to pass from the last interaction
#delete-interacted-users: true 
# An option for jobs that involves a *.txt to remove users/urls from it after they have been interacted with.

## Unfollow (unfollow jobs)
#unfollow: 10-20
#unfollow-any: 10-20

#funfollow-non-followers: 10-14

#unfollow-any-non-followers: 10-20
#unfollow-any-followers: 10-20
#unfollow-from-file: [usernames1.txt 7-15, usernames2.txt 6]

## Special modifier for unfollow jobs
#sort-followers-newest-to-oldest: false
unfollow-delay: 10

## Remove followers (active jobs)
#remove-followers-from-file: [remove1.txt 5-10, remove2.txt 6]

## Special modifier for remove followers
#delete-removed-followers: true

## Post Processing
# analytics: false # no more supported
#telegram-reports: false # for using telegram-reports you have also to configure telegram.yml in your account folder

## Special actions
# pre-script: pre_script_path_here
# post-script: post_script_path_here

##############################################################################
# Source Limits
##############################################################################

interactions-count: 1500-1900
likes-count: 1-2
likes-percentage: 0
stories-count: 1-2
stories-percentage: 30-40
carousel-count: 2-3
carousel-percentage: 60-70
max-comments-pro-user: 1-2
# comment-percentage: 30-40
pm-percentage: 100
interact-percentage: 100
follow-percentage: 100
follow-limit: 999
skipped-list-limit: 10-15
skipped-posts-limit: 5
fling-when-skipped: 0
min-following: 9

##############################################################################
# Total Limits Per Session
##############################################################################

total-likes-limit: 0
total-follows-limit: 999
total-unfollows-limit: 8
total-watches-limit: 0
total-successful-interactions-limit: 990-9950
total-interactions-limit: 990-9950
total-comments-limit: 0
total-pm-limit: 8-13
total-scraped-limit: 100-150

##############################################################################
# Ending Session Conditions
##############################################################################

end-if-likes-limit-reached: false
end-if-follows-limit-reached: true
end-if-watches-limit-reached: false
end-if-comments-limit-reached: false
end-if-pm-limit-reached: true

##############################################################################
# Scheduling
##############################################################################

#working-hours: [10.15-16.40, 18.15-23.46]
#time-delta: 0-24
#repeat: 280-320
total-sessions: -1 # -1 or commented for infinite sessions